# # default.wordpress.path = 'var/www/html/'


# default['wordpress']['db_user'] = 'wordpress'
# default['wordpress']['db_name'] = 'wordpress'
# default['wordpress']['db_password'] = 'password'
# default['wordpress']['destination'] = '/var/www/html/wordpress'

# default['wp']['server_name'] = 'atish@tecadmin.net'
# default['wp']['docroot']  ='/var/www/html/wordpress'
# default['wp']['host'] = 'localhost'
# default['wp']['username'] = 'root'
# default['wp']['password'] = 'Today@123'
# default['wp']['dbname'] = 'example_db'
# default['wp']['dbuser'] = 'example_user'
# default['wp']['dbpassword'] = 'Today@123'
# default['wp']['path'] = 'var/www/html/wordpress'

default['wordpress']['path'] = '/var/www/html/wordpress'
default['wordpress']['server_name'] = 'atish@tecadmin.net'
default['wordpress']['docroot']  ='/var/www/html/wordpress'
default['wordpress']['host'] = 'localhost'
default['wordpress']['username'] = 'root'
default['wordpress']['password'] = 'Today@123'
default['wordpress']['dbname'] = 'example_db'
default['wordpress']['dbuser'] = 'example_user'
default['wordpress']['dbpassword'] = 'Today@123'